create extension if not exists pgcrypto;
create table if not exists products (id bigint generated by default as identity primary key,name text not null,category text not null,price numeric(10,2) not null,description text default '',emoji text default '🍽️',popular boolean default false,active boolean default true,stock integer default 0,created_at timestamptz default now());
create table if not exists orders (id text primary key,customer_name text not null,customer_phone text default '',address text default '',order_type text not null,payment text not null,observation text default '',subtotal numeric(10,2) not null,delivery_fee numeric(10,2) default 0,discount numeric(10,2) default 0,total numeric(10,2) not null,status text not null default 'novo',items jsonb not null,table_id bigint,created_at timestamptz default now());
create table if not exists settings (id int primary key default 1,name text,city text,address text,whatsapp text,delivery_fee numeric(10,2) default 0,min_order numeric(10,2) default 0,free_delivery numeric(10,2) default 0,open boolean default true,updated_at timestamptz default now());
create table if not exists coupons (code text primary key,type text not null,value numeric(10,2) not null,active boolean default true);
create table if not exists staff_profiles (id uuid primary key references auth.users(id) on delete cascade,name text not null,role text not null default 'operador',active boolean default true,created_at timestamptz default now());
create table if not exists inventory_movements (id bigint generated by default as identity primary key,product_id bigint references products(id) on delete cascade,quantity integer not null,reason text,created_at timestamptz default now());
create table if not exists restaurant_tables (id bigint generated by default as identity primary key,name text not null unique,status text not null default 'livre',order_id text references orders(id));
alter table orders add column if not exists table_id bigint;
alter table products add column if not exists stock integer default 0;
insert into settings(id,name,city,address,whatsapp,delivery_fee,min_order,free_delivery,open) values(1,'Churrascaria Bohrer','Pelotas - RS','Praça Piratinino de Almeida, 74','5553999999999',7,0,0,true) on conflict(id) do nothing;
insert into coupons(code,type,value,active) values('BOHRER10','percent',10,true) on conflict(code) do nothing;
insert into restaurant_tables(name) select 'Mesa '||g from generate_series(1,12) g on conflict(name) do nothing;
-- Produção: habilite RLS e use Supabase Auth. As políticas abaixo são uma base segura para leitura pública do cardápio e criação de pedidos; escrita administrativa deve ser protegida por staff_profiles/roles.
alter table products enable row level security; alter table orders enable row level security; alter table settings enable row level security; alter table coupons enable row level security; alter table staff_profiles enable row level security; alter table inventory_movements enable row level security; alter table restaurant_tables enable row level security;
drop policy if exists products_public_read on products; create policy products_public_read on products for select using(active=true);
drop policy if exists settings_public_read on settings; create policy settings_public_read on settings for select using(true);
drop policy if exists coupons_public_read on coupons; create policy coupons_public_read on coupons for select using(active=true);
drop policy if exists orders_public_insert on orders; create policy orders_public_insert on orders for insert with check(true);
drop policy if exists orders_owner_read on orders; create policy orders_owner_read on orders for select using(true);
-- Para produção, substitua as políticas administrativas por verificações de auth.uid() em staff_profiles e não exponha service_role no frontend.
