create table if not exists products (id bigint generated by default as identity primary key, name text not null, category text not null, price numeric(10,2) not null, description text default '', emoji text default '🍽️', popular boolean default false, active boolean default true, created_at timestamptz default now());
create table if not exists orders (id text primary key, customer_name text not null, address text default '', order_type text not null, payment text not null, observation text default '', subtotal numeric(10,2) not null, delivery_fee numeric(10,2) default 0, discount numeric(10,2) default 0, total numeric(10,2) not null, status text not null default 'novo', items jsonb not null, created_at timestamptz default now());
create table if not exists settings (id int primary key default 1, name text, city text, address text, whatsapp text, delivery_fee numeric(10,2) default 0, updated_at timestamptz default now());
create table if not exists coupons (code text primary key, type text not null, value numeric(10,2) not null, active boolean default true);
insert into settings(id,name,city,address,whatsapp,delivery_fee) values(1,'Churrascaria Bohrer','Pelotas - RS','Praça Piratinino de Almeida, 74','5553999999999',7) on conflict(id) do nothing;
insert into coupons(code,type,value,active) values('BOHRER10','percent',10,true) on conflict(code) do nothing;
-- Para um protótipo público no Supabase, crie políticas RLS apropriadas. Não use service_role no navegador.
alter table products enable row level security; alter table orders enable row level security; alter table settings enable row level security; alter table coupons enable row level security;
create policy "public read active products" on products for select using (active=true);
create policy "public read settings" on settings for select using (true);
create policy "public read coupons" on coupons for select using (active=true);
create policy "public insert orders" on orders for insert with check (true);
create policy "public read orders" on orders for select using (true);
create policy "public update orders" on orders for update using (true) with check (true);
create policy "public admin product write" on products for all using (true) with check (true);
create policy "public settings write" on settings for update using (true) with check (true);
